"""init2

Revision ID: e52122d64602
Revises:
Create Date: 2023-08-17 15:43:50.607688

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e52122d64602"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bank_statement")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_statement",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "base64_bank_statement", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("contract_number", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("account_number", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("card", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("branch_of_the_bank", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("main_currency", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("period", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("client_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("transaction", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
            name="bank_statement_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="bank_statement_pkey"),
        sa.UniqueConstraint(
            "base64_bank_statement", name="bank_statement_base64_bank_statement_key"
        ),
    )
    # ### end Alembic commands ###
